version: '3.4'

services:
  web:
    image: savanasolutions/signalen-classification:0.3
    build:
      context: .
      target: signals-classification-web
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - SIGNALS_CATEGORY_URL=${SIGNALS_CATEGORY_URL}
      - MODELS_DIRECTORY=${MODELS_DIRECTORY}
      - TOP_N_PREDICTIONS=${TOP_N_PREDICTIONS}
    ports:
      - "8140:8000"
    volumes:
      - .:/app

  train:
    image: savanasolutions/signalen-classification-train:0.1
    build:
      context: .
      target: signals-classification-train
    volumes:
      - .:/app
